/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[24];
static double forc[0];
static double cons[0];
static double eventcounter[3];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define T12 parms[0] 
 #define KIN parms[1] 
 #define CSTMIN parms[2] 
 #define CSTDEL parms[3] 
 #define HILL parms[4] 
 #define EC50 parms[5] 
 #define y0_0 parms[6] 
 #define y1_0 parms[7] 
 #define y2_0 parms[8] 
 #define y3_0 parms[9] 
 #define y4_0 parms[10] 
 #define y5_0 parms[11] 
 #define y6_0 parms[12] 
 #define y7_0 parms[13] 
 #define y8_0 parms[14] 
 #define y9_0 parms[15] 
 #define y10_0 parms[16] 
 #define y11_0 parms[17] 
 #define y12_0 parms[18] 
 #define y13_0 parms[19] 
 #define y14_0 parms[20] 
 #define y15_0 parms[21] 
 #define y16_0 parms[22] 
 #define y17_0 parms[23] 
#define tmin range[0]
#define tmax range[1]


void odemodel_Notal_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=24;
	 odeparms(&N, parms);
	 for(int i=0; i<3; ++i) eventcounter[i] = 0;
}

void odemodel_Notal_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_Notal_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1e+00*((log(2e+00)/T12)*y[0]);
 	 ydot[1] = -1e+00*((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))*y[1])+1e+00*(KIN);
 	 ydot[2] = (-(log(2e+00)/T12))*(y[2]);
 	 ydot[3] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]))*(y[2])+(-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))))*(y[3]);
 	 ydot[4] = (-(log(2e+00)/T12))*(y[4]);
 	 ydot[5] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]))*(y[4])+(-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))))*(y[5]);
 	 ydot[6] = (-(log(2e+00)/T12))*(y[6])+log(2e+00)/pow(T12,2e+00)*y[0];
 	 ydot[7] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]))*(y[6])+(-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))))*(y[7]);
 	 ydot[8] = (-(log(2e+00)/T12))*(y[8]);
 	 ydot[9] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]))*(y[8])+(-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))))*(y[9])+1e+00-1e+00/(CSTMIN+CSTDEL)*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))*y[1];
 	 ydot[10] = (-(log(2e+00)/T12))*(y[10]);
 	 ydot[11] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]))*(y[10])+(-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))))*(y[11])+((KIN/(CSTMIN+CSTDEL))*(CSTDEL/pow(CSTMIN,2e+00)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))+KIN/pow((CSTMIN+CSTDEL),2e+00)*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))*y[1];
 	 ydot[12] = (-(log(2e+00)/T12))*(y[12]);
 	 ydot[13] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]))*(y[12])+(-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))))*(y[13])-(((KIN/(CSTMIN+CSTDEL))*(1e+00/CSTMIN*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))-KIN/pow((CSTMIN+CSTDEL),2e+00)*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))*y[1]);
 	 ydot[14] = (-(log(2e+00)/T12))*(y[14]);
 	 ydot[15] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]))*(y[14])+(-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))))*(y[15])-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL)*log((y[0]+1e-08)))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow(EC50,HILL)*log(EC50)+pow((y[0]+1e-08),HILL)*log((y[0]+1e-08)))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]);
 	 ydot[16] = (-(log(2e+00)/T12))*(y[16]);
 	 ydot[17] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]))*(y[16])+(-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))))*(y[17])+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow(EC50,(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1];

}

/** Jacobian of the ODE system **/
void odemodel_Notal_s_jacobian (int *n, double *t, double *y, double * df, double *RPAR, int *IPAR) {



double time = *t;
	 int i;
for(i=0; i<(*n) * (*n); i++) df[i] = 0.;
	 df[0] = -(log(2e+00)/T12);
 	 df[1] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]);
 	 df[3] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[3])+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(2e+00*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))/pow((pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)),2e+00)))*y[1]*(y[2]));
 	 df[5] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[5])+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(2e+00*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))/pow((pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)),2e+00)))*y[1]*(y[4]));
 	 df[6] = log(2e+00)/pow(T12,2e+00);
 	 df[7] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[7])+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(2e+00*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))/pow((pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)),2e+00)))*y[1]*(y[6]));
 	 df[9] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[9])+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(2e+00*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))/pow((pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)),2e+00)))*y[1]*(y[8])+1e+00/(CSTMIN+CSTDEL)*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]);
 	 df[11] = ((KIN/(CSTMIN+CSTDEL))*(CSTDEL/pow(CSTMIN,2e+00)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-CSTDEL/pow(CSTMIN,2e+00)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))+KIN/pow((CSTMIN+CSTDEL),2e+00)*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)))*y[1]-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[11])+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(2e+00*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))/pow((pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)),2e+00)))*y[1]*(y[10]));
 	 df[13] = -(((KIN/(CSTMIN+CSTDEL))*(1e+00/CSTMIN*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-1e+00/CSTMIN*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))-KIN/pow((CSTMIN+CSTDEL),2e+00)*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)))*y[1]+((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[13])+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(2e+00*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))/pow((pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)),2e+00)))*y[1]*(y[12])));
 	 df[15] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*log((y[0]+1e-08))+pow((y[0]+1e-08),HILL)*(1e+00/(y[0]+1e-08)))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL)*log((y[0]+1e-08)))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow(EC50,HILL)*log(EC50)+pow((y[0]+1e-08),HILL)*log((y[0]+1e-08)))+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*log((y[0]+1e-08))+pow((y[0]+1e-08),HILL)*(1e+00/(y[0]+1e-08))))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow(EC50,HILL)*log(EC50)+pow((y[0]+1e-08),HILL)*log((y[0]+1e-08)))*(2e+00*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))/pow((pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)),2e+00)))*y[1]+((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[15])+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(2e+00*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))/pow((pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)),2e+00)))*y[1]*(y[14])));
 	 df[17] = (KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow(EC50,(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow(EC50,(HILL-1e+00))*HILL)*(2e+00*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))/pow((pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)),2e+00))*y[1]-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[17])+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),((HILL-1e+00)-1e+00))*(HILL-1e+00)*HILL))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)*(2e+00*(pow((y[0]+1e-08),(HILL-1e+00))*HILL*(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))/pow((pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00)),2e+00)))*y[1]*(y[16]));
 	 df[19] = -((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))));
 	 df[21] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[2]));
 	 df[23] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[4]));
 	 df[25] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[6]));
 	 df[27] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[8])+1e+00/(CSTMIN+CSTDEL)*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))));
 	 df[29] = ((KIN/(CSTMIN+CSTDEL))*(CSTDEL/pow(CSTMIN,2e+00)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))+KIN/pow((CSTMIN+CSTDEL),2e+00)*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))-(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[10]);
 	 df[31] = -(((KIN/(CSTMIN+CSTDEL))*(1e+00/CSTMIN*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))-KIN/pow((CSTMIN+CSTDEL),2e+00)*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))))+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[12]));
 	 df[33] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL)*log((y[0]+1e-08)))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow(EC50,HILL)*log(EC50)+pow((y[0]+1e-08),HILL)*log((y[0]+1e-08)))/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))+(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[14]));
 	 df[35] = (KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow(EC50,(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))-(KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*(y[16]);
 	 df[38] = (-(log(2e+00)/T12));
 	 df[39] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]));
 	 df[57] = (-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))));
 	 df[76] = (-(log(2e+00)/T12));
 	 df[77] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]));
 	 df[95] = (-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))));
 	 df[114] = (-(log(2e+00)/T12));
 	 df[115] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]));
 	 df[133] = (-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))));
 	 df[152] = (-(log(2e+00)/T12));
 	 df[153] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]));
 	 df[171] = (-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))));
 	 df[190] = (-(log(2e+00)/T12));
 	 df[191] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]));
 	 df[209] = (-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))));
 	 df[228] = (-(log(2e+00)/T12));
 	 df[229] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]));
 	 df[247] = (-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))));
 	 df[266] = (-(log(2e+00)/T12));
 	 df[267] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]));
 	 df[285] = (-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))));
 	 df[304] = (-(log(2e+00)/T12));
 	 df[305] = (-((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]));
 	 df[323] = (-((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))));

}

/** Event function **/
void odemodel_Notal_s_myevent(int *n, double *t, double *y) {

	 double time = *t;

	 if(*t == 0 & eventcounter[0] == 0) {
		y[2] = y[2] + 0;
		y[4] = y[4] + 0;
		y[6] = y[6] + 0;
		y[8] = y[8] + 0;
		y[10] = y[10] + 0;
		y[12] = y[12] + 0;
		y[14] = y[14] + 0;
		y[16] = y[16] + 0;
		y[0] = y[0] + 2.0;
		eventcounter[0] = eventcounter[0] + 1.;
	 }

	 if(*t == 56.0 & eventcounter[1] == 0) {
		y[2] = y[2] + 0;
		y[4] = y[4] + 0;
		y[6] = y[6] + 0;
		y[8] = y[8] + 0;
		y[10] = y[10] + 0;
		y[12] = y[12] + 0;
		y[14] = y[14] + 0;
		y[16] = y[16] + 0;
		y[0] = y[0] + 2.0;
		eventcounter[1] = eventcounter[1] + 1.;
	 }

	 if(*t == 112.0 & eventcounter[2] == 0) {
		y[2] = y[2] + 0;
		y[4] = y[4] + 0;
		y[6] = y[6] + 0;
		y[8] = y[8] + 0;
		y[10] = y[10] + 0;
		y[12] = y[12] + 0;
		y[14] = y[14] + 0;
		y[16] = y[16] + 0;
		y[0] = y[0] + 2.0;
		eventcounter[2] = eventcounter[2] + 1.;
	 }


}
