/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[8];
static double forc[0];
static double cons[0];
static double eventcounter[3];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define T12 parms[0] 
 #define KIN parms[1] 
 #define CSTMIN parms[2] 
 #define CSTDEL parms[3] 
 #define HILL parms[4] 
 #define EC50 parms[5] 
 #define y0_0 parms[6] 
 #define y1_0 parms[7] 
#define tmin range[0]
#define tmax range[1]


void odemodel_Notal_initmod(void (* odeparms)(int *, double *)) {
	 int N=8;
	 odeparms(&N, parms);
	 for(int i=0; i<3; ++i) eventcounter[i] = 0;
}

void odemodel_Notal_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_Notal_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1e+00*((log(2e+00)/T12)*y[0]);
 	 ydot[1] = -1e+00*((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL)))*y[1])+1e+00*(KIN);

}

/** Jacobian of the ODE system **/
void odemodel_Notal_jacobian (int *n, double *t, double *y, double * df, double *RPAR, int *IPAR) {



double time = *t;
	 int i;
for(i=0; i<(*n) * (*n); i++) df[i] = 0.;
	 df[0] = -(log(2e+00)/T12);
 	 df[1] = -((KIN/(CSTMIN+CSTDEL))*((CSTDEL/CSTMIN)*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))-(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))*(pow((y[0]+1e-08),(HILL-1e+00))*HILL)/pow((pow(EC50,HILL)+pow((y[0]+1e-08),HILL)),2e+00))*y[1]);
 	 df[3] = -((KIN/(CSTMIN+CSTDEL))*(1e+00+(CSTDEL/CSTMIN)*(pow((y[0]+1e-08),HILL))/(pow(EC50,HILL)+pow((y[0]+1e-08),HILL))));

}

/** Event function **/
void odemodel_Notal_myevent(int *n, double *t, double *y) {

	 double time = *t;

	 if(*t == 0 & eventcounter[0] == 0) {
		y[0] = y[0] + 2.0;
		eventcounter[0] = eventcounter[0] + 1.;
	 }

	 if(*t == 56.0 & eventcounter[1] == 0) {
		y[0] = y[0] + 2.0;
		eventcounter[1] = eventcounter[1] + 1.;
	 }

	 if(*t == 112.0 & eventcounter[2] == 0) {
		y[0] = y[0] + 2.0;
		eventcounter[2] = eventcounter[2] + 1.;
	 }


}
